baseURL = "http://www.huiimy.ninja"
languageCode = "en-us"
title = "Hui is my ninja"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:day/:month/:year/:slug/"
    note = "/note/:day/:month/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 3
[[menu.main]]
    name = "Poem / 诗词"
    url = "/poems/"
    weight = 4
[[menu.main]]
    name = "Article"
    url = "/article"
    weight = 5
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 6
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 7
##[[menu.main]]
##    name = "Subscribe"
##    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Haozhe XU](http://www.huiimy.ninja) 2017"